Fix spell formulas, effect & crash issues in 7.72
nekiro/TFS-1.5-Downgrades pull request #56
Opened 2021-08-07 10:21 UTC by dnvd

Fix spell formulas, effect & crash issues in 7.72
This has been up for discussion if it should be fixed or not #45.

BUT...
The PR also includes a few crash fixes since some of the types threw an error when using some of the runes/spell.
Force wave, energy beams, HMMs, LMMs etc now also uses the correct effect/damage for this version.

2021-08-08 14:03 UTC, nekiro requested changes

2021-08-08 14:03 UTC, nekiro commented on data/spells/scripts/attack/poison_storm.lua
> +setConditionParam(condition, CONDITION_PARAM_DELAYED, 1)
please use tfs 1.x equivalents. This is old pre 1.x coding style.
setConditionParam is for example condition:setParameter
addDamageCondition is condition:addDamage

2021-08-15 18:27 UTC, dnvd commented
Ok, made some changes.

2021-08-16 11:12 UTC, nekiro requested changes

2021-08-16 11:12 UTC, nekiro commented on data/spells/scripts/attack/berserk.lua
> +	min = -(level * 2.2)
this value is global for some reason
same with max
use local before the names

2021-08-16 11:12 UTC, nekiro commented on data/spells/scripts/attack/poison_storm.lua
> +addCombatCondition(combat, condition)
combat:addCondition(condition)

2021-08-16 11:12 UTC, nekiro commented on data/spells/scripts/attack/poison_storm.lua
> +local condition = createConditionObject(CONDITION_POISON)
Condition(CONDITION_POISON)

2021-08-16 11:12 UTC, nekiro commented on data/spells/scripts/attack/poison_storm.lua
> +	min = -((level * 2) + (magicLevel * 3)) * 0.9
same as above, restore local, these two are globals now

2022-08-26 08:15 UTC, closed without merging